name: lcns
version: 0.1.0.0
github: "Litoprobka/lcns"
license: BSD2
author: "Litoprobka"
copyright: "2022 Peter Burtsev"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
language: GHC2021

default-extensions:
  - DuplicateRecordFields
  - NoImplicitPrelude
  - NoFieldSelectors
  - OverloadedStrings
  - OverloadedLabels
  - OverloadedRecordDot
  - RecordWildCards

dependencies:
  - base >= 4.8 && < 5
  - brick
  - bytestring
  - data-default
  - directory
  - filepath
  - filepath-bytestring
  - hinotify
  - optics
  - process
  - rawfilepath
  - relude
  - time
  - unix
  - unordered-containers
  - vty

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  lcns:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lcns
